export const s = {
  root:    { display:"flex", width:"100%", height:"100vh", background:"#FAFAF9", fontFamily:"'Inter',system-ui,sans-serif", overflow:"hidden", color:"#1C1917" },
  sidebar: { width:200, background:"#1C1917", display:"flex", flexDirection:"column", padding:"16px 12px", gap:4, flexShrink:0, overflowY:"auto" },
  logo:    { display:"flex", alignItems:"center", gap:8 },
  logoMark:{ width:26, height:26, background:"#E7E5E4", borderRadius:6, display:"flex", alignItems:"center", justifyContent:"center", fontSize:13, fontWeight:700, color:"#1C1917" },
  logoTxt: { color:"#E7E5E4", fontSize:14, fontWeight:600, letterSpacing:"-0.01em" },
  avatar:  { width:28, height:28, borderRadius:"50%", background:"#292524", color:"#A8A29E", fontSize:12, fontWeight:600, display:"flex", alignItems:"center", justifyContent:"center", cursor:"pointer", objectFit:"cover" },
  label:   { fontSize:10, color:"#57534E", letterSpacing:".1em", textTransform:"uppercase", padding:"0 6px", marginBottom:4 },
  spacePill:{ display:"flex", alignItems:"center", gap:8, width:"100%", background:"#292524", border:"1.5px solid", borderRadius:8, padding:"8px 10px", cursor:"pointer", color:"#E7E5E4", fontFamily:"inherit", marginBottom:4 },
  drop:    { position:"absolute", top:"100%", left:0, right:0, background:"#292524", borderRadius:8, border:"1px solid #3F3C3A", zIndex:100, overflow:"hidden", marginTop:2 },
  dropItem:{ display:"flex", alignItems:"center", gap:8, width:"100%", background:"transparent", border:"none", padding:"9px 12px", cursor:"pointer", color:"#A8A29E", fontSize:13, fontFamily:"inherit" },
  dropManage:{ width:"100%", background:"transparent", border:"none", padding:"9px 12px", cursor:"pointer", color:"#57534E", fontSize:12, fontFamily:"inherit", textAlign:"left" },
  div:     { height:1, background:"#292524", margin:"8px 0" },
  navBtn:  { display:"flex", alignItems:"center", gap:8, background:"transparent", border:"none", borderRadius:7, padding:"8px 10px", cursor:"pointer", color:"#78716C", fontFamily:"inherit", width:"100%" },
  navActive:{ background:"#292524", color:"#E7E5E4" },
  tagPill: { background:"transparent", border:"none", borderRadius:6, padding:"6px 10px", fontSize:12, cursor:"pointer", color:"#78716C", fontFamily:"inherit", textAlign:"left", width:"100%" },
  staleHint:{ fontSize:11, color:"#92400E", background:"#FEF3C7", borderRadius:6, padding:"6px 10px", marginBottom:4 },
  main:    { flex:1, minWidth:0, overflow:"hidden", display:"flex", flexDirection:"column" },
  listHead:{ padding:"14px 16px 10px", borderBottom:"1px solid #E7E5E4", display:"flex", flexDirection:"column", gap:8 },
  badge:   { fontSize:11, color:"#A8A29E", background:"#F5F5F4", borderRadius:20, padding:"2px 8px" },
  searchBox:{ flex:1, padding:"8px 12px", border:"1px solid #E7E5E4", borderRadius:7, fontSize:13, background:"#FAFAF9", color:"#1C1917", outline:"none", fontFamily:"inherit" },
  ctrlBtn: { padding:"7px 10px", border:"1px solid #E7E5E4", borderRadius:7, fontSize:12, cursor:"pointer", background:"#FAFAF9", color:"#78716C", fontFamily:"inherit", whiteSpace:"nowrap", transition:"all .15s" },
  dateInp: { border:"1px solid #E7E5E4", borderRadius:6, padding:"5px 8px", fontSize:12, fontFamily:"inherit", color:"#1C1917", background:"#FAFAF9", outline:"none" },
  clearBtn:{ background:"transparent", border:"none", fontSize:12, color:"#A8A29E", cursor:"pointer", fontFamily:"inherit", textDecoration:"underline" },
  empty:   { color:"#A8A29E", fontSize:13, padding:"40px 20px", textAlign:"center" },
  noteRow: { display:"flex", justifyContent:"space-between", gap:16, padding:"13px 10px", borderRadius:8, borderBottom:"1px solid #F5F5F4" },
  rowAction:{ background:"transparent", border:"none", color:"#A8A29E", cursor:"pointer", padding:4, borderRadius:4, display:"flex", alignItems:"center", justifyContent:"center", transition:"color .15s" },
  tinyTag: { fontSize:10, padding:"2px 6px", borderRadius:4, background:"#F5F5F4", color:"#78716C" },
  staleBar:{ background:"#FEF3C7", padding:"10px 20px", display:"flex", alignItems:"center", gap:10, fontSize:12, color:"#92400E", flexShrink:0 },
  staleBtn:{ background:"transparent", border:"1px solid #D97706", borderRadius:5, padding:"3px 10px", fontSize:11, cursor:"pointer", color:"#92400E", fontFamily:"inherit" },
  backBtn: { background:"transparent", border:"none", color:"#78716C", fontSize:13, cursor:"pointer", fontFamily:"inherit" },
  titleInp:{ border:"none", outline:"none", fontSize:22, fontWeight:700, color:"#1C1917", background:"transparent", fontFamily:"inherit", letterSpacing:"-0.02em", width:"100%" },
  contentArea:{ flex:1, border:"none", outline:"none", fontSize:14, color:"#44403C", background:"transparent", fontFamily:"inherit", lineHeight:1.7, resize:"none", width:"100%" },
  toolSec: { display:"flex", flexDirection:"column", gap:8, minWidth:140 },
  toolLbl: { fontSize:10, color:"#A8A29E", letterSpacing:".1em", textTransform:"uppercase" },
  addTagBtn:{ fontSize:12, padding:"3px 8px", borderRadius:6, border:"1px dashed #D6D3D1", background:"transparent", color:"#A8A29E", cursor:"pointer", fontFamily:"inherit" },
  pickerWrap:{ position:"absolute", bottom:"100%", left:0, background:"#fff", border:"1px solid #E7E5E4", borderRadius:8, padding:6, zIndex:50, minWidth:180, boxShadow:"0 8px 24px rgba(0,0,0,.1)" },
  pickerInput:{ width:"100%", border:"1px solid #E7E5E4", borderRadius:6, padding:"6px 8px", fontSize:12, fontFamily:"inherit", outline:"none", marginBottom:4, boxSizing:"border-box" },
  pickerItem:{ display:"block", width:"100%", background:"transparent", border:"none", padding:"6px 8px", fontSize:12, cursor:"pointer", fontFamily:"inherit", textAlign:"left", borderRadius:5, color:"#44403C" },
  chk:     { width:17, height:17, borderRadius:4, border:"1.5px solid #D6D3D1", display:"flex", alignItems:"center", justifyContent:"center", cursor:"pointer", flexShrink:0 },
  taskInp: { flex:1, border:"none", borderBottom:"1px solid #E7E5E4", background:"transparent", fontFamily:"inherit", fontSize:13, color:"#1C1917", outline:"none", padding:"3px 0" },
  topBar:  { display:"flex", alignItems:"center", justifyContent:"space-between", padding:"12px 16px", background:"#1C1917", borderBottom:"1px solid #292524", flexShrink:0 },
  menuBtn: { background:"transparent", border:"none", cursor:"pointer", padding:4, display:"flex", alignItems:"center" },
  mNav:    { position:"fixed", bottom:0, left:0, right:0, height:64, background:"#1C1917", borderTop:"1px solid #292524", display:"flex", alignItems:"center", justifyContent:"space-evenly", zIndex:200 },
  mNavBtn: { display:"flex", flexDirection:"column", alignItems:"center", gap:3, background:"transparent", border:"none", color:"#57534E", cursor:"pointer", fontFamily:"inherit", padding:"6px 16px", transition:"color .15s" },
  fab:     { width:56, height:56, borderRadius:"50%", border:"none", cursor:"pointer", display:"flex", alignItems:"center", justifyContent:"center", flexShrink:0, boxShadow:"0 4px 20px rgba(0,0,0,.4)", marginBottom:22 },
  drawerOverlay:{ position:"fixed", inset:0, background:"rgba(0,0,0,.6)", zIndex:400, backdropFilter:"blur(2px)" },
  drawer:  { position:"absolute", top:0, left:0, bottom:0, width:"78vw", maxWidth:300, background:"#1C1917", display:"flex", flexDirection:"column", padding:"16px 14px", gap:4, overflowY:"auto" },
  saveToast:{ position:"fixed", top:20, left:"50%", transform:"translateX(-50%)", background:"#fff", border:"1px solid #D1FAE5", borderRadius:8, padding:"8px 18px", fontSize:13, fontWeight:500, color:"#065F46", display:"flex", alignItems:"center", gap:8, boxShadow:"0 4px 16px rgba(0,0,0,.1)", zIndex:600, animation:"fadeInOut 1.5s ease" },
  iconBtn: { background:"transparent", border:"none", color:"#57534E", fontSize:16, cursor:"pointer", padding:4 },
  smRow:   { display:"flex", alignItems:"center", gap:8, padding:"8px 10px", borderRadius:8, background:"#FAFAF9", border:"1px solid #F5F5F4" },
  smEditBtn:{ background:"transparent", border:"1px solid #E7E5E4", borderRadius:6, padding:"4px 10px", fontSize:12, cursor:"pointer", color:"#78716C", fontFamily:"inherit" },
  smInp:   { border:"1.5px solid #E7E5E4", borderRadius:7, padding:"8px 12px", fontSize:14, fontFamily:"inherit", color:"#1C1917", outline:"none", background:"#FAFAF9" },
  smOk:    { background:"#1C1917", color:"#fff", border:"none", borderRadius:6, padding:"7px 14px", fontSize:13, cursor:"pointer", fontFamily:"inherit", fontWeight:500 },
  smCan:   { background:"transparent", border:"1px solid #E7E5E4", borderRadius:6, padding:"7px 14px", fontSize:13, cursor:"pointer", fontFamily:"inherit", color:"#78716C" },
  eBtn:    { background:"transparent", border:"1px solid transparent", borderRadius:6, padding:"4px 7px", fontSize:16, cursor:"pointer" },
  eBtnA:   { background:"#F5F5F4", border:"1px solid #E7E5E4" },
  cBtn:    { width:20, height:20, borderRadius:"50%", border:"2.5px solid transparent", cursor:"pointer" },
  cBtnA:   { border:"2.5px solid #1C1917" },
  tvHead:  { padding:"16px 20px 12px", borderBottom:"1px solid #E7E5E4", display:"flex", flexDirection:"column", gap:10, flexShrink:0 },
  tvList:  { flex:1, overflowY:"auto", padding:"8px 20px 80px" },
  tvRow:   { display:"flex", alignItems:"flex-start", gap:12, padding:"12px 0", borderBottom:"1px solid #F5F5F4" },
  tagChip: { fontSize:12, padding:"4px 10px", borderRadius:20, border:"1px solid #E7E5E4", background:"transparent", color:"#78716C", cursor:"pointer", fontFamily:"inherit" },
  setSection:{ borderBottom:"1px solid #F5F5F4", paddingBottom:16 },
  setLabel: { fontSize:10, color:"#A8A29E", letterSpacing:".1em", textTransform:"uppercase" },
};
